### PR TITLE
Update and rename raspi-config to ev3dev-config

### PR DESCRIPTION
**Pull request by MolarAmbiguity**
Renamed raspi-config.
Changed link inside file.

### CODE REVIEW

**Comment by MolarAmbiguity** [comment]
Hm, Github seems to have inluded my extra changes as well? I was trying to do two separate Pull Requests, as per dlech's instructions.

**Comment by dlech** [comment]
It would be better if you could squash all of the README changes into one commit.

**Comment by dlech** [comment]
And the rename doesn't have to be a separate pull request, just a separate commit. They way you have it now is fine.

**Comment by MolarAmbiguity** [comment]
Feedback acquired and noted.

At the moment the script has the CONFIG variable set to /boot/config.txt, will this be the same on ev3dev?

**Comment by dlech** [comment]
Yes and no. We are working on getting ev3dev working on Raspberry Pi, so don't delete it. But ev3dev on the EV3 will not have a config.txt, so disable it for now.

**Comment by dlech** [comment]
Also, the file has moved to `/boot/flash/config.txt` for now.

**Comment by MolarAmbiguity** [comment]
So you will just have ev3dev actually on the pi, or  just use the drivers?

**Comment by dlech** [comment]
We will have our own SD card image for RPi that includes the same packages we use on the EV3 (with some extras) and a custom kernel with the ev3dev drivers.

**Comment by MolarAmbiguity** [comment]
So is there a way to squash multiple commits into one that I'm missing?

**Comment by dlech** [comment]
From a command line, `git rebase --interactive 110ccd1` will to the trick. `110ccd1` is the commit id of your first commit.

When you run this command, it will open a file in a text editor that contains instructions. You will need to change `pick` to `squash` (or just `s` is OK) on the 3 most recent commits. This will cause all 4 README commits to be squashed into one.

**Pull request closed without merging**
